name: push

on: 
  push:
    branches: 
      - main
  pull_request:

env:
  # For setup-rust, see https://github.com/moonrepo/setup-rust/issues/22
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  install-and-build-shaders:
    strategy:
      matrix: 
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run: 
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - uses: moonrepo/setup-rust@v1
      - run: rustup default stable 
      - run: rustup update
      - run: cargo install --path crates/cargo-gpu
      - run: cargo gpu install
      - run: git clone https://github.com/Rust-GPU/shader-crate-template.git
      - run: cargo gpu build --shader-crate shader-crate-template --output-dir shaders
      - run: ls -lah shaders
      - run: cat shaders/manifest.json

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: moonrepo/setup-rust@v1
      - run: cargo clippy
